### PR TITLE
switch from travis to github actions

### PR DESCRIPTION
**Pull request by elelay**

### CODE REVIEW

**Comment by elelay** [comment]
@thp seems to work well. I've combined test and publish to not publish when test fails.

I've created a elelay user on pypi and test pypi.

It uses an API token to push to [test.pypi.org](https://test.pypi.org/project/podcastparser/),
added as a [repository secret](https://github.com/gpodder/podcastparser/settings/secrets/actions).

Could you create an API token for the pypi gpodder user and as it as a secret named `PYPI_API_TOKEN`?

Thanks,

**Comment by auouymous** [comment]
What are the three hyphens at top for?

It might be better to drop the version from `- name: Set up Python 3.9`, so only the `python-version: 3.9` line must be changed on bumps.

Why not run tests on pull requests?

```
on: [push, pull_request]

...

    if: >-
      (github.event_name == 'push') && (
      startsWith(github.ref, 'refs/tags') ||
      (github.ref == 'refs/heads/master') ||
      (github.ref == 'refs/heads/github_actions'))
```

**Comment by auouymous** [comment]
Does a `TEST_PYPI_API_TOKEN` secret also need to be created?

**Comment by elelay** [comment]
> Does a `TEST_PYPI_API_TOKEN` secret also need to be created?

Already done.

**Comment by elelay** [comment]
> What are the three hyphens at top for?
> 

It signals the yaml start of document.

> These dashes indicate the start of a new YAML document. YAML supports multiple documents, and compliant parsers will recognize each set of dashes as the beginning of a new one. 
[source](https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started)

**Comment by elelay** [comment]
> It might be better to drop the version from `- name: Set up Python 3.9`, so only the `python-version: 3.9` line must be changed on bumps.

yes

> 
> Why not run tests on pull requests?
> 

It was running twice for each push (and the 2nd publication to test pypi failed because the file already existed),
maybe because it was a PR for a branch of the repository.

Sure, we would like the test phase to be run on external pull requests!
We shall see if it's necessary on external pull requests.

**Comment by elelay** [comment]
> Why not run tests on pull requests?

It should do now, when the branch is not from podcastparser own repo (it will have to be tested, once the PR is merged)

**Comment by auouymous** [comment]
It looks like the hyphens are only needed if you have multiple documents in the same file, to separate them. But this file only has a single document, and the gpodder file works fine without them.

Why wrap all but the first expressions in parenthesis?
```
       github.event_name == 'push' ||
       (github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name)

       github.event_name == 'push' && (
         (github.ref == 'refs/heads/master') ||
         (github.ref == 'refs/heads/github_actions'))
```

So the test was running twice because you pushed to a branch in the repo and then again for the pull request? If so, that will need to be fixed in gpodder as well.

**Comment by thp** [comment]
> @thp seems to work well. I've combined test and publish to not publish when test fails.
> 
> I've created a elelay user on pypi and test pypi.
> 
> It uses an API token to push to [test.pypi.org](https://test.pypi.org/project/podcastparser/),
> added as a [repository secret](https://github.com/gpodder/podcastparser/settings/secrets/actions).
> 
> Could you create an API token for the pypi gpodder user and as it as a secret named `PYPI_API_TOKEN`?

Added `PYPI_API_TOKEN` for `podcastparser` on PyPI (created using my "thp" user on PyPI).

**Comment by auouymous** [comment]
This bumped the version to 0.6.7 but it hasn't been tagged yet.

Also, https://podcastparser.readthedocs.io/en/latest/ hasn't been updated since 0.6.4.

**Comment by elelay** [comment]
Yes, I'm so eager to try the publish hook on tags ;-)

**Comment by elelay** [comment]
Actually I don't know how to update https://podcastparser.readthedocs.io

**Comment by auouymous** [comment]
The PyPI page has (outdated #35) instructions on releasing, too bad the readthedocs page doesn't.

**Comment by elelay** [comment]
I can't re-add the podcastparser project to readthedocs because it's already there.
@thp any thoughts on this? Maybe hosting doc on readthedocs was not deemed that useful in the end?

**Pull request merged**
