### PR TITLE
switch from nose to pytest

### PR DESCRIPTION
**Pull request by pgajdos**
nose is deprecated and will not work with python 3.9.

### CODE REVIEW

**Comment by elelay** [comment]
Thanks for the PR!
Any idea why travis tests failed on python 2.7, 3.5, 3.7, pypy?

**Comment by pgajdos** [comment]
`pkg_resources.VersionConflict: (pytest 4.3.1 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('pytest>=4.6'))`

Not sure so far how to fix it, I am not much familiar with travis.

**Comment by pgajdos** [comment]
Tried and succeded.

**Comment by pgajdos** [comment]
Not sure about appveyor, though.

**Comment by auouymous** [comment]
Try adding pytest to https://github.com/gpodder/podcastparser/blob/master/appveyor.yml#L24

**Comment by auouymous** [comment]
Travis doesn't test python 3.3, but appveyor does and fails.

**Comment by thp** [comment]
PyTest 4.6 seems to support only Python >= 3.4 (and it's the last version to support 2.7):

https://docs.pytest.org/en/latest/py27-py34-deprecation.html

At this point, it's probably fine to drop Python 2 support (which isn't supported since beginning of the year) and require Python >= 3.5 (which was initially released nearly 5 years ago).

**Comment by elelay** [comment]
Merged, thanks!

**Pull request merged**
