### PR TITLE
fail gracefully on invalid inputs for mktime on Win

### PR DESCRIPTION
**Pull request by wamserma**

### CODE REVIEW

**Comment by thp** [comment]
..wonder how hard it would be to write a custom `mktime_tz()` in Python that can deal with these issues? Would be nice to have the same features on Windows as we have on macOS/Linux (i.e. be able to return a valid number in either case).

**Comment by thp** [comment]
For Python 3.6, this is the implementation of `mktime_tz`:
```
def mktime_tz(data):                                                                                                     
    """Turn a 10-tuple as returned by parsedate_tz() into a POSIX timestamp."""                                          
    if data[9] is None:                                                                                                  
        # No zone info, so localtime is better assumption than GMT                                                       
        return time.mktime(data[:8] + (-1,))                                                                             
    else:                                                                                                                
        t = calendar.timegm(data)                                                                                        
        return t - data[9]                                                                                               
```

The `time.mktime()` is from the C library AFAIK, whereas `calendar.timegm()` is:

```
def timegm(tuple):                                                                                                       
    """Unrelated but handy function to calculate Unix timestamp from GMT."""                                             
    year, month, day, hour, minute, second = tuple[:6]                                                                   
    days = datetime.date(year, month, 1).toordinal() - _EPOCH_ORD + day - 1                                              
    hours = days*24 + hour                                                                                               
    minutes = hours*60 + minute                                                                                          
    seconds = minutes*60 + second                                                                                        
    return seconds                                                                                                       
```

Can you use that info to come up with a portable solution?

**Comment by wamserma** [comment]
This is quick fix to keep feeds in gPodder updating. Any pubdates before epoch are likely wrong (there aren't many podcast from the 60's iirc), so I'm fine with defaulting to my local epoch (whatever that is).
For a portable solution (producing negative values) you need to specify first how it should behave (local or UTC and so on, see http://stackoverflow.com/questions/2956886/python-calendar-timegm-vs-time-mktime or http://stackoverflow.com/questions/15447632/python-convert-utc-time-tuple-to-utc-timestamp) and then, what about podcast from the 19th century? That would be beyond minus End of Time (seen from epoch). Dates can be a PITA and defaulting to epoch (timestamp = 0) in the case of a parsing error is a simple and clean solution. Let's keep it that way.

**Comment by thp** [comment]
Well, 19th century is beyond minus end-of-time if you assume 32-bit `time_t`.

I'm happy with falling back to zero if there's a parsing error or some other out-of-bounds (and your patch would work fine for that), but the normal cases including the ones you have with 1960 should be supported, since they are supported fine on Linux/macOS, and we shouldn't provide a worse experience just because someone is on Windows.

Or in other words, I'd like to take this opportunity to fix this for Windows users in addition to adding the zero fallback instead of just adding the zero fallback without thinking of where the edge cases are.

**Comment by wamserma** [comment]
I don't think there are many users on Windows that care whether podcasts episodes with a pubdate before epoch are sorted correctly or just as if they were published at epoch as long as they show up at all and do not block updating of the feed. :) I wouldn't regard it this as a worse UX. If anyone really has a problem with that, a PR can easily be submitted. The beauty of open source.

**Comment by thp** [comment]
Ok, so I've checked with Windows and Python 2.7, the implementation of `mktime_tz()` is a bit different in Python 2.7, using `time.mktime()` in both cases (with and without timezone). On Python 3 and Windows, the unit test (with time zone specification, so that it uses `calendar.timegm()`) works without problems. Given that we eventually switch to Python 3, and taking your comments into account, I'll merge this one.

**Comment by thp** [comment]
Note that with your AppVeyor changes, we actually needed to fix the unit tests, so now I've added a way for the doctest to work with Python 2 on Windows (by doing what Python 3 does). So now with the newest podcastparser, you should see the 1960 dates even on Windows + Python 2 :) And all other dates should properly be coalesced to zero in case there's some error.

**Pull request merged**
